
version: 2

jobs:
    before_script:
      docker:
        - image: circleci/ruby:2.4.1
      
      steps:
        - checkout
        - run: echo "Executing cppLint"
        
    run_cpplint:
      docker:
        - image: ubuntu:18.04
    
      steps:
        - checkout
        - run: ls -a
        - run: "apt-get update -y"
        - run: "apt-get install -y python-pip"
        - run: "python -m pip install cpplint"
        - run: "cpplint --filter=-whitespace,-legal/copyright,-readability/multiline_comment,-readability/braces,-build/include_order,-build/c++11,-build/include_what_you_use,-runtime/string --linelength=160 wind_plugin.hpp"
                
    after_script:
      docker:
        - image: circleci/ruby:2.4.1
    
      steps:
        - checkout
        - run: echo "Execution finished"

workflows:
    version: 2
    cpplint:
      jobs:
        - before_script
        - run_cpplint:
            requires:
              - before_script
        - after_script:
            requires:
              - run_cpplint